source 'https://rubygems.org'

# Specify your gem's dependencies in compass-core.gemspec
gemspec

gem 'pry'
gem 'diff-lcs', '~> 1.1.2'
gem 'true', "~> 0.2.3"
gem 'timecop'
gem 'test-unit'
gem 'warning'
