require "bundler/gem_tasks"
require "rake/testtask"
require 'warning'

Warning.process do |w|
  if w.include?("The $start value for random")
    $stderr.puts(warning)
  elsif w.include?("keyword")
    $stderr.puts(warning)
  else
    nil
  end
end


Rake::TestTask.new do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end
