# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ 'stable' ]
  pull_request:
    branches: [ 'stable' ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - core/Gemfile
          - cli/gemfiles/sass_3_3.gemfile
          - cli/gemfiles/listen_2.gemfile
        exclude:
          - gemfile: cli/gemfiles/sass_3_3.gemfile
            component: core
          - gemfile: cli/gemfiles/listen_2.gemfile
            component: core
          - gemfile: core/Gemfile
            component: cli

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
      CI_TEST: ${{ matrix.component }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: cd $CI_TEST && bundle exec rake
